"""added user models

Revision ID: fcbc70a69a18
Revises: 
Create Date: 2022-10-23 23:50:40.910410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcbc70a69a18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    pass
    # ### end Alembic commands #

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
